language: node_js
node_js:
  - 8
  - 9
cache:
  directories:
    - node_modules
after_success:
  # Make release with semantic-release if needed
  - npm install -g semantic-release travis-deploy-once
  - travis-deploy-once "semantic-release --analyze-commits ./analyzeCommits --verify-release ./verifyRelease --generate-notes ./generateNotes"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
